apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-go
    input:
      slackApiToken: "apikey"
      slackNotifyMessage: "Order something?"
      slackChanelID: "chanelid"
      pollServiceName: ""
      pollServicePort: 80
      pollServiceTargetPort: 80
      ingressName: ""
      ingressHostName: ""
      providerConfigRef: ""
      deploymentName: ""
      deploymentServiceAccount: ""
      deploymentImage: ""
      configMap: ""