apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-go
    input:
      providerConfigRef: "default"
      deploymentName: "collect"
      deploymentImage: "ghcr.io/kndpio/kndp/slack-collector:0.1.0"