apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-template-go
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-go
    input:
      slackAPIToken: ""
      slackNotifyMessage: ""
      slackChanelID: ""
      providerConfigRef: ""
      deploymentName: ""
      deploymentServiceAccount: ""
      deploymentImage: ""
      configMap: ""