apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: poll-composition
spec:
  compositeTypeRef:
    apiVersion: kndp.io/v1alpha1
    kind: Poll
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-go
    input:
      apiVersion: kndp.io/v1alpha1
      kind: Poll
      providerConfigRef: "kndp-kubernetes-provider-config"
      deploymentImage: "ghcr.io/kndpio/function-poll/slack-collector:d7a4b"
      cronJobImage: "ghcr.io/kndpio/function-poll/slack-notify:d7a4b"
      jobImage: "ghcr.io/kndpio/function-poll/slack-order:d7a4b"
      deploymentName: "slack-collector"
      serviceAccountName: "slack-collector"