apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: poll-composition
spec:
  compositeTypeRef:
    apiVersion: kndp.io/v1alpha1
    kind: Poll
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-template-go
    input:
      providerConfigRef: "default"
      deploymentImage: "ghcr.io/kndpio/kndp/slack-collector:0.1.0"
      deploymentName: "collect"
